/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Office.glb 
*/

import React, { useRef } from 'react';
import { useGLTF, useVideoTexture } from '@react-three/drei';
import {motion} from "framer-motion-3d";

import * as THREE from "three";

export function Office(props) {
  const textureVSCode= useVideoTexture("textures/vscode.mp4");
  const {section}=props;
  const { nodes, materials } = useGLTF('models/Office.glb')

return (
  <group {...props} dispose={null}>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Floor.geometry}
      material={materials.Floor}
      position={[0, -0.123, 0]}
    />
    {/*<mesh
      castShadow
      receiveShadow
      geometry={nodes.Poster.geometry}
      material={materials.Poster}
      position={[-1.914, 2.444, -0.862]}
/>*/}
    <motion.mesh
      castShadow
      receiveShadow
      geometry={nodes.Table.geometry}
      material={materials.Table}
      position={[0.002, 0.842, -1.324]}
      scale={[1, 1.05, 1]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["Table.Handle"]}
        position={[1.602, 0.196, 0.535]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.952]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials["Table.Handle"]}
        position={[1.602, -0.059, 0.535]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.952]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials["Table.Handle"]}
        position={[1.602, -0.313, 0.535]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.952]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials["Table.Handle"]}
        position={[1.602, -0.559, 0.535]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.952]}
      />
      <group
        position={[0.692, 0.343, 0.164]}
        rotation={[0, 0.016, 0]}
        scale={[0.786, 0.748, 0.786]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials["Laptop.Bottom"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials["Laptop.Keys.Bottom"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Key.geometry}
          material={materials["Laptop.Keys"]}
          position={[-0.209, 0.05, -0.159]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key001.geometry}
            material={materials["Laptop.Keys"]}
            position={[-0.014, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key002.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.008, 0, 0.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key003.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.008, 0, 0.121]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key004.geometry}
            material={materials["Laptop.Keys"]}
            position={[-0.014, 0, 0.162]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key005.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.027, 0, 0.162]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key006.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.069, 0, 0.162]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key007.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.114, 0, 0.162]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key008.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.201, 0, 0.162]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key009.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.288, 0, 0.162]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key010.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.332, 0, 0.162]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key011.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.37, 0, 0.171]}
            scale={[0.839, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key012.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.405, 0, 0.171]}
            scale={[0.839, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key014.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.439, 0, 0.171]}
            scale={[0.839, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key015.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.405, 0, 0.152]}
            scale={[0.839, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key016.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.093, 0, 0.122]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key017.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.135, 0, 0.122]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key018.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.177, 0, 0.122]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key019.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.22, 0, 0.122]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key020.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.262, 0, 0.122]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key021.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.304, 0, 0.122]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key022.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.346, 0, 0.122]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key023.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.388, 0, 0.122]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key024.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.073, 0, 0.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key025.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.114, 0, 0.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key026.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.157, 0, 0.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key027.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.199, 0, 0.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key028.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.241, 0, 0.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key029.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.283, 0, 0.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key030.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.325, 0, 0.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key031.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.367, 0, 0.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key032.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.388, 0, 0.081]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key033.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.028, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key034.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.07, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key035.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.113, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key036.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.155, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key037.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.198, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key038.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.24, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key039.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.283, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key040.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.326, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key041.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.368, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key042.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.41, 0, 0.04]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key043.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.055, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key044.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.098, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key045.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.14, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key046.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.183, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key047.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.225, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key048.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.267, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key049.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.309, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key050.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.351, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key051.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.393, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Key052.geometry}
            material={materials["Laptop.Keys"]}
            position={[0.434, 0, 0]}
          />
        </mesh>
        <group position={[0, 0.225, -0.334]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube044.geometry}
            material={materials["Laptop.Bottom"]}
          />
       
        </group>
        <mesh
            geometry={nodes.Screen.geometry}
            position={[0.027, 0.23, -0.245]}
            scale={[1,1,1]}
          >
            <meshBasicMaterial map={textureVSCode} toneMapped={false} />
          </mesh>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_Shelf.geometry}
        material={materials.Table}
        position={[1.599, -0.003, 0.016]}
        scale={[1, 0.952, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_Top.geometry}
        material={materials.Table}
        position={[-0.003, -0.283, 1.339]}
        scale={[1, 0.952, 1]}
      />
    </motion.mesh>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Sheets.geometry}
      material={materials["Bed Sheet"]}
      position={[-0.096, 0, -0.096]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bed_Frame.geometry}
        material={materials["Bed Frame"]}
        position={[-0.102, 0.592, 0.803]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mattress.geometry}
        material={materials.Bedsheets}
        position={[-0.874, 0.571, -0.425]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pillow.geometry}
        material={materials["Bed Sheet"]}
        position={[-0.887, 0.863, -1.384]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Small_Pillow.geometry}
        material={materials.Pillow}
        position={[-1.134, 0.88, -1.069]}
        rotation={[-0.015, 0.154, 0.105]}
      />
    </mesh>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Window_Frame.geometry}
      material={materials["Window.Frame"]}
      position={[0.8, 2.556, -1.949]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Window.Curtain"]}
        position={[0, 1.094, 0.053]}
        rotation={[0, 0, -Math.PI / 2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curtains.geometry}
          material={materials["Window.Curtain"]}
          position={[1.094, 0, 0.004]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["Window.Curtain"]}
          position={[1.406, 0, 0]}
        />
      </mesh>
      <group position={[0, -0.427, -0.142]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials["Window.Frame"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials["Window.Light"]}
        />
      </group>
      <group position={[0, 0, -0.058]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials["Window.Frame"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Window.Light"]}
        />
      </group>
    </mesh>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Chair.geometry}
      material={materials.Chair}
      position={[0.717, 1.257, -0.288]}
      rotation={[0, -0.121, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials["Chair.Bottom"]}
        position={[0.004, -0.887, -0.193]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials["Chair.Bottom"]}
        position={[0.003, -0.681, -0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials["Chair.Wheel"]}
        position={[0.453, -1.093, -0.193]}
        rotation={[Math.PI / 2, 0, -0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials["Chair.Wheel"]}
        position={[0.228, -1.093, -0.576]}
        rotation={[Math.PI / 2, 0, -1.117]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials["Chair.Wheel"]}
        position={[-0.22, -1.093, -0.578]}
        rotation={[Math.PI / 2, 0, -2.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials["Chair.Wheel"]}
        position={[-0.45, -1.093, -0.193]}
        rotation={[Math.PI / 2, 0, -0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials["Chair.Wheel"]}
        position={[-0.223, -1.093, 0.198]}
        rotation={[Math.PI / 2, 0, -0.976]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials["Chair.Wheel"]}
        position={[0.226, -1.093, 0.197]}
        rotation={[Math.PI / 2, 0, -2.126]}
      />
    </mesh>
    <motion.group
     scale={[0, 0, 0]}
     animate={{
       scale: section === 0 ? 1 : 0,
     }}
     position={[-1.268, 3.339, -1.867]} rotation={[Math.PI / 2, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials.Frames}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025_1.geometry}
        material={materials["Frame.Two"]}
      />
      <group position={[0.659, -0.028, 0.262]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021.geometry}
          material={materials.Frames}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_1.geometry}
          material={materials["Frame.One"]}
        />
      </group>
      <group position={[-0.112, 0, 0.516]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={materials.Frames}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_1.geometry}
          material={materials["Frame.Three"]}
        />
      </group>
      <group position={[0.403, 0, 0.972]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials.Frames}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={materials["Frame.Four"]}
        />
      </group>
    </motion.group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Lamp.geometry}
      material={materials["Stand.Lamp"]}
      position={[-0.143, 0.133, 1.389]}
      rotation={[0, 0.368, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials["Stand.Lamp"]}
        position={[0, 1.998, -0.368]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials["Stand.Lamp"]}
        position={[-0.001, 1.791, -0.002]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamp_Head001.geometry}
        material={materials["Stand.Lamp"]}
        position={[0, 2.421, -1.077]}
        rotation={[-0.365, 0.026, -0.138]}
      />
    </mesh>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.MouseTop.geometry}
      material={materials.Mouse}
      position={[1.079, 1.252, -1.136]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MouseBody.geometry}
        material={materials.Mouse}
        position={[0, 0.002, 0]}
        scale={0.656}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MouseScrollWheel.geometry}
        material={materials["Mouse.Wheel"]}
        position={[0.001, 0.022, -0.04]}
        scale={0.656}
      />
    </mesh>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Table_Lamp.geometry}
      material={materials["Table.Lamp"]}
      position={[1.537, 1.241, -1.595]}
      rotation={[0, 0.476, 0]}
      scale={1.354}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials["Table.Lamp"]}
        position={[0.042, 0.106, 0.003]}
        scale={[0.006, 0.098, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials["Table.Lamp"]}
        position={[0.082, 0.194, 0.005]}
        scale={0.246}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials["Table.Lamp"]}
        position={[0.026, 0.283, 0.002]}
        scale={[0.006, 0.098, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials["Table.Lamp"]}
        position={[-0.03, 0.372, -0.002]}
        scale={0.246}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials["Table.Lamp"]}
        position={[-0.05, 0.379, -0.003]}
        scale={[0.005, 0.012, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamp_Head.geometry}
        material={materials["Table.Lamp"]}
        position={[-0.142, 0.373, -0.011]}
        rotation={[0.152, -0.026, 0.038]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0, 0.013, 0]}
        scale={0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={materials["Table.Lamp"]}
        position={[-0.077, 0.381, -0.007]}
      />
    </mesh>
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book.geometry}
      material={materials["White Book"]}
      position={[0.237, 1.259, -1.555]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Small_Bool.geometry}
      material={materials["Red Book"]}
      position={[0.251, 1.299, -1.528]}
      rotation={[0, 0.185, 0]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book001.geometry}
      material={materials["Red Book"]}
      position={[-1.72, 2.889, 0.042]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book002.geometry}
      material={materials["Red Book"]}
      position={[-1.72, 2.889, 0.125]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book003.geometry}
      material={materials["White Book"]}
      position={[-1.72, 2.863, 0.222]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book004.geometry}
      material={materials["Blue Book"]}
      position={[-1.711, 2.706, 0.845]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book005.geometry}
      material={materials["Red Book"]}
      position={[-1.732, 2.743, 0.774]}
      rotation={[0, -0.304, 0]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book006.geometry}
      material={materials["White Book"]}
      position={[-1.732, 1.834, 1.441]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book007.geometry}
      material={materials["Blue Book"]}
      position={[-1.732, 1.91, 1.441]}
      rotation={[0, 0.643, 0]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book008.geometry}
      material={materials["White Book"]}
      position={[-0.494, 1.736, -1.766]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book009.geometry}
      material={materials["Blue Book"]}
      position={[-0.588, 1.736, -1.766]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Big_Book010.geometry}
      material={materials["Red Book"]}
      position={[-0.683, 1.736, -1.766]}
    />
    <motion.mesh
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
      castShadow
      receiveShadow
      geometry={nodes.Catus.geometry}
      material={materials.Pot}
      position={[-1.742, 1.787, 0.937]}
      rotation={[0, 1.489, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere004.geometry}
        material={materials.Catus}
        position={[0.002, 0.21, -0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={materials.Catus}
        position={[0.112, 0.275, -0.002]}
        rotation={[0, 0, -0.491]}
      />
    </motion.mesh>
    <group position={[-1.194, 1.54, -1.709]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle009.geometry}
        material={materials["Candle.Body"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle009_1.geometry}
        material={materials["Candle.Top"]}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Shelf_1.geometry}
      material={materials.Shelf}
      position={[-1.707, 2.638, 0.574]}
      rotation={[0, 1.571, 0]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Shelf_2.geometry}
      material={materials.Shelf}
      position={[-1.707, 1.747, 1.192]}
      rotation={[0, 1.571, 0]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Shelf_3.geometry}
      material={materials.Shelf}
      position={[-1.007, 1.49, -1.709]}
    />
    <group position={[-0.99, 1.54, -1.709]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={materials["Candle.Body"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006_1.geometry}
        material={materials["Candle.Top"]}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Wall_Tile.geometry}
      material={materials.Floor}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Walls.geometry}
        material={materials.Walls}
      />
    </mesh>
  </group>
);
  
}

useGLTF.preload('models/Office.glb');
